name: Generate Pacman Contribution Graph

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: dhruvchhabra29
          output_branch: output
          generate_dark_mode: true